server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mydatabase"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

payment:
  url: "https://script.google.com/macros/s/AKfycbyQdQ6RRVmYOv80xyZOXvhE5w_eeBisPE8_aDgpgKXW6wHZmXq6CA9BBiYO0bvJfcWl/exec"